[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -c 'uvicorn app.api.main:app --host 0.0.0.0 --port ${PORT:-8000}'"
restartPolicyType = "ON_FAILURE"


[service]

name = "tai-xiu-analyzer"


